### ISSUE TITLE
Change conversion amount

### ISSUE THREAD

**Issue by jenniferhub** [ultraleettech/currency-rates#1]
Good afternoon, and you can do something like this

RUB/USD
1000 => 65.9534

You default to 1.

**Comment by leetdev** [comment]
That's because it's not a currency conversion library, you can easily do conversion yourself (simple multiplication will suffice). However, we can add that feature for convenience.

**Comment by SteeinGit** [comment]
add please,

Example:
http://dropmefiles.com/kg0Zx

**Comment by jenniferhub** [comment]
add please,

Example:
http://dropmefiles.com/kg0Zx

**Comment by leetdev** [comment]
Feature added and released. See readme for usage instructions.
